use anyhow::{Context, Result};
use base64::Engine;
use clap::Parser;
use gps_core::ProofReceipt;
use methods::GPS_GUEST_ID;
use risc0_zkvm::Receipt;
use std::fs;

/// GPS, Real STARK proof verifier.
///
/// Unlike verifier.html (which only checks the image_id whitelist), this tool
/// calls risc0_zkvm::Receipt::verify() which actually checks the STARK seal.
/// A dev_mode proof (RISC0_DEV_MODE=1 at generation time) will fail here.
#[derive(Parser)]
#[command(name = "risc0-verifier", about = "GPS, Cryptographic STARK proof verifier")]
struct Args {
    /// Path to a GPS proof JSON file (output of gps-host prove --output <file>)
    proof: String,

    /// Override the expected image_id (64 hex chars). Defaults to the latest GPS_GUEST_ID.
    #[arg(long)]
    image_id: Option<String>,
}

fn main() -> Result<()> {
    let args = Args::parse();

    let raw = fs::read_to_string(&args.proof)
        .with_context(|| format!("Cannot read: {}", args.proof))?;

    let proof: serde_json::Value = serde_json::from_str(&raw)
        .context("File is not valid JSON")?;

    let seal_b64 = proof["seal"].as_str()
        .context("Missing 'seal' field in proof JSON")?;

    let is_dev_mode = proof["metadata"]["dev_mode"].as_bool().unwrap_or(false);
    let proof_image_id = proof["image_id"].as_str().unwrap_or("unknown");
    let meta = &proof["metadata"];

    println!("----------------------------------------------");
    println!(" GPS, STARK Proof Verifier");
    println!("----------------------------------------------");
    println!(" File       : {}", args.proof);
    println!(" Image ID   : {}", proof_image_id);
    println!(" Proof time : {}s", meta["proof_time_seconds"].as_f64()
        .map(|s| format!("{:.1}", s)).unwrap_or_else(|| "?".into()));
    if is_dev_mode {
        println!(" [!]  Dev mode proof, this will NOT pass real STARK verification");
    }

    // Determine which image_id to verify against
    let expected_id: [u32; 8] = match &args.image_id {
        Some(hex) => hex_to_image_id(hex)
            .context("--image-id must be 64 hex characters (32 bytes)")?,
        None => GPS_GUEST_ID,
    };

    let seal_bytes = base64::engine::general_purpose::STANDARD
        .decode(seal_b64)
        .context("Invalid base64 in seal field")?;

    let receipt: Receipt = bincode::deserialize(&seal_bytes)
        .context("Cannot deserialize receipt. Was it generated by risc0-zkvm 3.0.x?")?;

    print!(" Verifying STARK seal... ");
    match receipt.verify(expected_id) {
        Ok(()) => {
            println!("VALID");
            println!("----------------------------------------------");
            match receipt.journal.decode::<ProofReceipt>() {
                Ok(r) => {
                    println!(" Domain   : {}", r.server_domain);
                    println!(" Timestamp: {}", r.server_timestamp);
                    println!(" Session  : {}", r.session_id);
                    println!(" Anchor   : {}", r.trust_anchor);
                    if !r.field_results.is_empty() {
                        for fr in &r.field_results {
                            let icon = if fr.predicate_result { "OK" } else { "FAIL" };
                            println!(" {} {}, {}", icon, fr.field_label, fr.predicate_statement);
                        }
                    } else {
                        println!(" Statement: {}", r.predicate_statement);
                        println!(" Result   : {}", if r.predicate_result { "TRUE" } else { "FALSE" });
                    }
                }
                Err(e) => {
                    println!(" (journal decode failed: {}, raw bytes follow)", e);
                    println!(" Journal  : {:?}",
                        &receipt.journal.bytes[..receipt.journal.bytes.len().min(64)]);
                }
            }
            println!("----------------------------------------------");
        }
        Err(e) => {
            println!("INVALID");
            println!("----------------------------------------------");
            eprintln!(" Error: {}", e);
            std::process::exit(1);
        }
    }

    Ok(())
}

/// Parse a 64-char hex image_id string into the [u32; 8] format used by risc0_zkvm.
/// Each 8-char chunk is one u32, formatted by `format!("{:08x}", val)`: i.e. big-endian display.
fn hex_to_image_id(hex: &str) -> Result<[u32; 8]> {
    anyhow::ensure!(hex.len() == 64, "expected 64 hex chars, got {}", hex.len());
    let mut arr = [0u32; 8];
    for (i, chunk) in hex.as_bytes().chunks(8).enumerate() {
        let s = std::str::from_utf8(chunk).context("non-UTF8 in hex")?;
        arr[i] = u32::from_str_radix(s, 16).context("invalid hex digit")?;
    }
    Ok(arr)
}
